### ISSUE TITLE
Registery Object not present for the Ankh Shield. Client doesn't start.

### ISSUE THREAD

**Issue by TJdot** [Partonetrain/familiarweapons-architechtury#4]
![image_2024-12-16_192642037](https://github.com/user-attachments/assets/1d6c1218-af6e-4c66-b8f9-d62f47e852db)
 Crash Log:
[crash-2024-12-16_19.14.13-fml.txt](https://github.com/user-attachments/files/18158539/crash-2024-12-16_19.14.13-fml.txt)

**Comment by Partonetrain** [comment]
Does this happen with a fully updated FamiliarWeapons? You are using v1.0.3, the mod is on v1.1.2

**Comment by TJdot** [comment]
oh i grabbed the wrong crash log, it does though.
[crash-2024-12-16_18.43.02-fml.txt](https://github.com/user-attachments/files/18158628/crash-2024-12-16_18.43.02-fml.txt)
That was me trying to backtrack to fix it, my bad.

**Comment by Partonetrain** [comment]
Hmm. I can reproduce this, but I have no idea how this could be happening. The client code that is crashing should only ever be called *after* the item is registered: 
https://github.com/Partonetrain/familiarweapons-architechtury/blob/main/common/src/main/java/info/partonetrain/familiarweapons/FamiliarWeapons.java#L35

**Comment by TJdot** [comment]
Can't say I have any idea either. I just felt a need to report it to you.
The game did boot with the original, but then it crashed my server, which is something addressed by the one update. But then the game stopped booting and the server was fine.

**Comment by Partonetrain** [comment]
I appreciate the report. I will ask around and see if I can figure out the issue.

**Comment by Partonetrain** [comment]
I am uploading 1.1.3 to CurseForge and Modrinth, let me know if that fixes the issue once the file is approved

**Comment by TJdot** [comment]
Can say I am able to load in both game and server. :) Horray.
thanks for the fast response/fix.
